# Generated by Django 4.1.3 on 2022-12-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_login_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id1',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
