# Generated by Django 4.1.3 on 2022-12-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_login_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
