# Generated by Django 4.1.3 on 2022-12-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login_last_name_login_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
