# Generated by Django 4.1.3 on 2022-12-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_login_id1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('github_url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'Registro',
            },
        ),
    ]
